Ft python approximation curve
j042/SplineLib pull request #1
Opened 2021-09-16 14:16 UTC by jzwar

# Overview
Small Change that enables approximations of splines to a point cloud. The code reuses as much of the existing code as possible and introduces only little modifications to the original structure.  Implementation based on NURBS-book. Allows for arbitrary B-Splines and returns Residual

# Testing
Implementation has been tested with respect to python code from [NURBS-Python](https://github.com/orbingol/NURBS-Python)

2021-09-16 15:31 UTC, jzwar commented on Sources/Fittings/interpolate.cpp
> +  }
```suggestion
  // Add P0 at front and Pm at end (might be inefficient)
  control_points.resize(control_points.size() + dim * 2);
  for (int i{n_ctps_v * dim - 1}; i >= 0; i--) {
    control_points[i+dim] = control_points[i];
  }
  for (int i{0}; i < dim ; i++) {
    control_points[i]  = points[i];
    control_points[(n_ctps_v +1) * dim + i] = points[(num_points-1) * dim + i];
  }
```

This is actually more efficient, my bad...

2021-09-21 08:34 UTC, j042 requested changes
Thank you! Looking forward to approximate curves.

2021-09-21 13:28 UTC, jzwar commented on Sources/Fittings/utils.hpp
> +        ++span;
In this particular case there is no difference. I just prefer this over the other stylewise :D

2021-09-21 13:39 UTC, jzwar commented on Sources/Fittings/utils.hpp
> +    delete pts_u, pts_v;
According to [this](https://stackoverflow.com/questions/1484739/how-to-properly-delete-a-pointer-to-array) you seem to be correct. I will change this

2021-09-21 13:48 UTC, j042 commented on Sources/Fittings/fitting.cpp
> +                      int& num_points,
alignment

2021-09-21 13:50 UTC, j042 requested changes
1.0

2021-09-21 14:17 UTC, merged